import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme/theme-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Header />
          <main className="flex flex-col flex-1 py-24 px-8 min-h-screen overflow-y-auto overflow-x-hidden bg-secondary/20">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
